AdobeDocs/adobe-io-events

- src/pages/guides/using/marketo-user-audit-data-stream-setup.md
CET-1021
Event structure change, wrapped event details in the body element.
Remove the user field.
Add the userId to support easy track of the user details.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
> Update Marketo User Audit Data Stream Docs for event structure change.

- src/pages/support/tracing.md
Document max limits for request and response body in Debug Tracing
> Document max limits for request and response body in Debug Tracing.

- src/pages/guides/index.md
> updating aio-lib-events sdk ref link to latest sdk npm version

- src/pages/guides/api/eventsingress_api.md
- src/pages/guides/sdk/sdk_publish_events.md
- src/pages/support/faq.md
document our events ingress API throttling policy
> CI-5227 document our events ingress API throttling policy

- src/pages/guides/index.md
This PRs clarification around signature verification of challenge deliveries. Also did some other minor reformatting and rephrasing.
`npm run dev`
> Add clarification around signature verification of challenge deliveries

- src/pages/common/retry-doc.md
- src/pages/guides/index.md
- src/pages/support/faq.md
This PR does the following:
1. Amends guarantees around retry intervals
2. Uses a common page for all of retry related content
`npm run dev`
> Amending retry interval guarantees

- src/pages/guides/index.md
- src/pages/guides/runtime_webhooks.md
Documenting I/O Events digital signature verification steps properly for java and node js based apps
See thread https://adobeio.slack.com/archives/C6841FMPU/p1647972756218329 for motivation
> documenting the signature verification steps properly for both java and node js apps

- static/events-api-reference.yaml
> removing type and parent_client_id fields from api references

- src/pages/guides/using/aem/aem_workspace_setup.md
This PR adds correct format for configuring metascopes. 
A customer was recently facing [this issue](https://adobeio.slack.com/archives/C6841FMPU/p1656073206097009?thread_ts=1656064438.091959&cid=C6841FMPU).
`npm run dev`
> Add correct format for configuring metascopes

- gatsby-ssr.js
This PR is purely for demonstration purposes and shall be used to demonstrate injection of a seamless credential creation widget.
> Inject seamless credential creation widget

- gatsby-ssr.js
> Download latest js

- gatsby-ssr.js
> Use file from GH pages instead

- src/pages/guides/using/index.md
This PR updates the listing of events available via I/O Events. 
- Asset Events was not listed in the [using guides landing page](https://developer.adobe.com/events/docs/guides/using/).
`npm run dev`
> Update listing of available events

- src/pages/guides/api/journaling_api.md
Update UI instructions in the Adobe I/O Events Journaling API doc as in [CI-5606](https://jira.corp.adobe.com/browse/CI-5606)
https://jira.corp.adobe.com/browse/CI-5606
The documentation steps were outdated.
> CI-5606 Update UI instructions in the Adobe I/O Events Journaling API doc

- src/pages/guides/api/registration_api.md
- static/events-api-reference.yaml
Update the documentation for registration V2 API in Adobe I/O Events API
We have migrated from V1 to V2 version of Registration API. The swagger has been updated accordingly.
> Update V2 Registration Adobe I/O Events API

- gatsby-config.js
- src/pages/guides/autoregistrations.md
- src/pages/guides/autosubscriptions.md
- src/pages/index.md
Added article about app builder auto subscriptions to events
https://jira.corp.adobe.com/browse/DEVX-2258
> DEVX-2258: Added article about app builder events auto subscription

- src/pages/guides/using/asset-events/asset-events-landing.md
- static/events-api-reference.yaml
Io Events Doc - fixing broken link, fixing registrations api def
> fixing broken link, fixing registrations api def

- gatsby-config.js
- src/pages/common/receiving-events-for-users-doc.md
- src/pages/guides/index.md
- src/pages/guides/using/asset-events/asset-events-configuration.md
- src/pages/index.md
- src/pages/support/index.md
This PR fixes the following:
- Removes a deleted link from sidenav
- Fixes a whitespace issue at https://developer.adobe.com/events/docs/#prerequisites
| Title  | Image |
| ------------- | ------------- |
| Before  | ![before](https://user-images.githubusercontent.com/6910192/208865438-0029d099-9f1a-4812-86d0-ddef3184ce43.png)  |
| After  |  ![after](https://user-images.githubusercontent.com/6910192/208865673-1b562658-3194-4936-af5b-42a430e4bda6.png) |
- Restructures the "Receiving Events For Users" section to add more hints. Also leveraged the same doc in "Asset Events Configuration" page. This was done based on a [customer request](https://experienceleaguecommunities.adobe.com/t5/adobe-i-o-events-questions/triggering-https-ims-na1-adobelogin-com-ims-authorize-v1/m-p/564171/highlight/true …
> Broken link + Enhancement to "Receiving Events For Users" section

- .github/scripts/get-path-prefix.js
adding missing path-prefix file
adding missing path-prefix file
> update path-prefix file

- src/pages/guides/api/registration_api.md
- src/pages/support/faq.md
Adding detail for creating runtime webhook registrations in AIO Events
Adding context for `runtime_action` in creating webhook registrations.
Adding faq for debugging successful activations of runtime actions.
For `runtime_action` context
For faq on runtime_action debugging
> adding runtime action info for registration v2 api

- src/pages/guides/using/marketo/marketo-data-streams-developer-guidelines.md
- src/pages/guides/using/marketo/marketo-observability-data-stream-setup.md
- src/pages/guides/using/marketo/marketo-user-audit-data-stream-setup.md
- static/redirections.js
Minor updates to documentation for Marketo Data Streams including links, typos, and redirect
[CET-2570](https://jira.corp.adobe.com/browse/CET-2570)
> Updates to Marketo data streams documentation

- src/pages/guides/api/registration_api.md
- static/events-api-reference.yaml
This PR does the following:
- Fixed a broken link in https://developer.adobe.com/events/docs/guides/api/registration_api/
- [Added delivery_type in curl code snippets](https://github.com/AdobeDocs/adobe-io-events/commit/7dfaac2ec489ef74188fdfc88de2022efd21c492) as that is a required parameter now
- [Updated the API reference page](https://github.com/AdobeDocs/adobe-io-events/commit/d142539c4ab6312502ab206a660061e9e9ce807f) to add `delivery_type` as a required parameter.
- [Replaced "webhook registration" with "event registration" to make it more generic](https://github.com/AdobeDocs/adobe-io-events/pull/115/commits/7564c3a7fd917c392399d16799076a080fbef73f)
- [Minor formatting and wording changes](https://github.com/AdobeDocs/adobe-io-events/pull/115/commits/4aecefecdd3570bebe2650f1113226ac …
> Update createRegistration API docs

- src/pages/support/faq.md
I/O Events Faq update: changing webhook batch size limit
We recently [updated](https://jira.corp.adobe.com/browse/CI-6481) our ingress adapters batch size limit to align with the Amazon EventBridge entries limit so that we don't run into the limit error exception while delivery event bridge deliveries. 
Keeping the doc updated accordingly.
`npm run dev`
> faq update: changing batch size limit

- src/pages/common/retry-doc.md
Updates the I/O Events doc on webhook state change logic. See [CI-6711](https://jira.corp.adobe.com/browse/CI-6711)
To reflect the functional logic change around webhook state management in the I/O Events public doc.
See jira CI-6711
> updating doc for webhook state change new criteria logic

- src/pages/guides/index.md
This PR removes the reference to sample webhook server that is not maintained anymore. Since we support asynchronous validation, we can point customers to [webhook.site](https://webhook.site/) for easier local development and debugging.
`yarn run dev`
| S. No | Screenshot |
|--------|--------|
| 1 | ![your first webhook](https://github.com/user-attachments/assets/3636b3ba-a545-4496-b9c4-152c00ff2cf5) |
> Remove reference to sample webhook server

- src/pages/guides/using/marketo/marketo-user-audit-data-stream-setup.md
Just a small update to the payload structure of User Audit Data Stream (UADS)
Since migrating away from Smarts and onto Kairos, the payload structure of our UADS events have changes slightly. This change reflects those changes, as well an anonymizes some internal OrgIDs.
The payload structure of UADS has changes, and the documentation was out of sync.
Built locally and previewed.
> CET-3109 Updates UADS documentation.

- yarn.lock
This PR updates dependency for AEM docs.
```
yarn remove experience-manager-apis
yarn add experience-manager-apis@https://github.com/AdobeDocs/experience-manager-apis
npm run dev
```
> Update AEM docs dependency

- .github/workflows/deploy.yml
This PR does the following:
1. [Triggers deployment on push to main branch automatically](https://github.com/AdobeDocs/adobe-io-events/commit/e08b244ebe9f9ef2c82a5bb6a8d74bfe809515c2)
2. [Updates default params for the manual dispatch of deployment action](https://github.com/AdobeDocs/adobe-io-events/commit/2a2c323ebe211683039d446d28c01c94db4a1cca)
> Update github actions

- src/pages/guides/using/marketo/marketo-data-streams.md
Removes the "(Beta)" text from UADS, and updates the wording around the data stream states.
This updates the status of User Audit Data Stream to reflect that it is now GA.
N/A
Simple text change
> Removes the "(Beta)" text from UADS

- gatsby-config.js
- src/pages/guides/using/index.md
> InDesign API Events Tile Update

- static/events-api-reference.yaml
Update API reference page:
- Add missing status codes
- Add missing params to the relevant APIs
- Add missing API endpoints
- Remove empty descriptions
- Use consistent terminology
Cannot be tested locally
> Update API reference

- static/events-api-reference.yaml
Update provider input model with missing fields
Locally rendered the swagger spec
> Update provider input model with missing fields
